### ISSUE TITLE
willekeurig selectie

### ISSUE THREAD

**Issue by jossiee** [gruijter/com.gruijter.clusterlights#1]
misschien is het mogelijk om in de settings checkboxes te maken welke mode's er langs komen als je willekeurige mode gebruikt.

tevens lijkt het er op dat de mode AlwaysOff ook meegenomen wordt in de willekeurige mode

**Comment by gruijter** [comment]
Good Idea. I Will look intocht this!

**Comment by gruijter** [comment]
Het zit er in: https://github.com/gruijter/com.gruijter.clusterlights
Veel plezier ermee :)
