### ISSUE TITLE
Flows werken niet.

### ISSUE THREAD

**Issue by beatrix18** [gruijter/com.gruijter.clusterlights#5]
Goede morgen,
Vorig jaar de app met veel plezier gebruikt.
Zowel de laatste versie als ook de bèta app installeren prima en vinden de verlichting.
Kan ook met de knop en slider het licht bedienen. Een flow geeft groen vinkje bij testen maar doet het verder niet. Heb de boel al volledig gedeinstalleerd en herstart. Heb geen bluetooth verbinding via mijn smartphone met de verlichting. Enig idee?

Groeten,
Peter

**Comment by gruijter** [comment]
Give your Home a PTP (power off - 30s wait - power on). And dont try multiple commands too fast. The BLE of Homey is not very stable unfortunately...
And keep the lights close to Homey (10m is probably too far).

**Comment by beatrix18** [comment]
Sorry for posting in Dutch. I am new on GitHub.
I have tried all the tips but unfortunately is the result still the same.
In both the latest as well the beta app, I can manually switch on/off and dim the light.
Flows however, do nothing.
I placed Homey close to the light and tried not to stress him/her/it.
I appreciate your work, success!

**Comment by gruijter** [comment]
No worries on the Dutch 🤗

Weird. Maybe try a flow where you give the same command several times, with 30s delay (so 0, 30,60, 90). I also noticed that sometimes Homey just is not able to pass the command from a flow. But triggering the flow multiple times eventually does the job for me. As said, Homey and BLE is not very stable 😢

**Comment by beatrix18** [comment]
Yes, very unstable! 
I have the latest software versions, distance short, did resets and always the same result. Google routines are almost here in the Netherlands an that's my last hope because spoken dim commands with Google assistant do work most of the time.

**Comment by gruijter** [comment]
Should be solved in v 1.0.2

https://homey.app/a/com.gruijter.clusterlights/test/

Please let me know if this fixes it for you.

**Comment by beatrix18** [comment]
Just installed your new app. Did a few tests and......it works!! Thanks and a happy new year Robin!

**Comment by gruijter** [comment]
Super. Thx 4 testing and happy NY!
