### ISSUE TITLE
Possible to add another standard ?

### ISSUE THREAD

**Issue by JorisBodin** [gruijter/com.gruijter.clusterlights#6]
Hello :)

I have a BT low led ruban, it's work with this app: https://play.google.com/store/apps/details?id=com.xiaoyu.hlight

It's possible to add this standards? And how help you for this?

Thank you :)

**Comment by gruijter** [comment]
I might be able to add it. I would need a light to do the development and testing. Are you willing to buy one for me?

**Comment by JorisBodin** [comment]
Yes i can

**Comment by gruijter** [comment]
Easiest is if you make sufficient donation to my paypal, and I order one. Where can I order one? Im in NL.

https://www.paypal.com/paypalme/gruijter

Beware: I need to reverse engineer the BLE from the light. I cannot guarantee that I will succeed.

**Comment by JorisBodin** [comment]
I paid 11€ for 10m from Belgium, from china it's less expensive.
But 5m is 9€
https://a.aliexpress.com/_BTrF6B

**Comment by JorisBodin** [comment]
I paid 😊

**Comment by gruijter** [comment]
Ordered a set on aliexpress for some 14 euro including shipping. Wont arrive before xmas though 😯

**Comment by JorisBodin** [comment]
In fact, delivery from Belgium is not available for the Netherlands. Completely stupid.

Thanks you 😊

**Comment by gruijter** [comment]
Received them yesterday. Been reverse engeneering all night 🤪
And I found the most important commands. Now I need to implement a new driver for that in Homey. Especially the RGB control is new for my app. Will work on that the coming nights.

**Comment by gruijter** [comment]
It is ready. I'm actually quite pleased with the result :)

It took quite some time to get the RGB control working in Homey, but with some help I managed to fix that this afternoon too.

You can already install it from here: https://homey.app/a/com.gruijter.clusterlights/test/

Let me know if it works for you too

**Comment by JorisBodin** [comment]
Ho very fast. 
Thank you
I test immediately

**Comment by JorisBodin** [comment]
It's perfect 👍 
Good design
I found an inconsistency in the colours picker. If I click for example on red and then click on one of the red variants, they are all much too light.
And I couldn't find out how to display only white

Ps: do you like this led ribbon for this price? :D

**Comment by gruijter** [comment]
To pick 'white' you need to go to the center of the colour picker (the version with the continuous coloured circle). The brightness can be controlled with the dimmer slider. That the real colour deviates from the colour picker has more to do with the not so high quality of the led strip. But for the money it is a very nice gadget. I think my son will use it to have fun in his bedroom.
